services:
  - type: web
    name: online-service-for-applicants
    env: static
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildCommand: CI=false react-scripts build
    startCommand: serve -s build